/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import DataModel.*;
/**
 *
 * @author Steven
 */
public class LauncherGUI extends javax.swing.JFrame {

    
    private static RARDocument doc;
    /**
     * Creates new form LauncherGUI
     */
    public LauncherGUI(RARDocument doc_) 
    {
        this.doc = doc_;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LaunchButton = new javax.swing.JButton();
        CreateEventButton = new javax.swing.JButton();
        ReviewEventInfoButton = new javax.swing.JButton();
        AddMemberButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LaunchButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LaunchButton.setText("Launch Event");
        LaunchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LaunchButtonMouseClicked(evt);
            }
        });

        CreateEventButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CreateEventButton.setText("Create Event");
        CreateEventButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateEventButtonMouseClicked(evt);
            }
        });

        ReviewEventInfoButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ReviewEventInfoButton.setText("Review Event Info");
        ReviewEventInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReviewEventInfoButtonMouseClicked(evt);
            }
        });

        AddMemberButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddMemberButton.setText("Add Member");
        AddMemberButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMemberButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReviewEventInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LaunchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CreateEventButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddMemberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CreateEventButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LaunchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReviewEventInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddMemberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LaunchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaunchButtonMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaunchEventGUI(doc).setVisible(true);
            }
        });
    }//GEN-LAST:event_LaunchButtonMouseClicked

    private void CreateEventButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateEventButtonMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateEventGUI(doc).setVisible(true);
            }
        });
    }//GEN-LAST:event_CreateEventButtonMouseClicked

    private void ReviewEventInfoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReviewEventInfoButtonMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReviewInfoGUI(doc).setVisible(true);
            }
        });
    }//GEN-LAST:event_ReviewEventInfoButtonMouseClicked

    private void AddMemberButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMemberButtonMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMemberGUI(doc).setVisible(true);
            }
        });
    }//GEN-LAST:event_AddMemberButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LauncherGUI(new RARDocument()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMemberButton;
    private javax.swing.JButton CreateEventButton;
    private javax.swing.JButton LaunchButton;
    private javax.swing.JButton ReviewEventInfoButton;
    // End of variables declaration//GEN-END:variables
}
